package:
  name: conda-build-missing
  version: 0.1.0

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
  run:
    - python
    - conda
    - conda-build

test:
  commands:
    - conda-build-missing -h
  imports:
    - conda_build_missing

